name: Deploy EC2 CloudFormation Stack

on:
  workflow_dispatch:
    inputs:
      stack_name:
        description: 'CloudFormation stack name'
        required: true
        default: 'manus-ec2-browser'
      region:
        description: 'AWS region'
        required: false
        default: 'us-east-1'
      instance_type:
        description: 'EC2 instance type'
        required: false
        default: 't2.medium'
        type: choice
        options:
          - t2.micro
          - t2.small
          - t2.medium
          - t2.large

jobs:
  deploy-cloudformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}
      
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/cloudformation-template.json \
            --stack-name ${{ github.event.inputs.stack_name }} \
            --parameter-overrides \
              InstanceType=${{ github.event.inputs.instance_type }} \
              KeyName=manus-ec2-key \
            --capabilities CAPABILITY_IAM
      
      - name: Get CloudFormation outputs
        run: |
          echo "Stack outputs:"
          aws cloudformation describe-stacks \
            --stack-name ${{ github.event.inputs.stack_name }} \
            --query "Stacks[0].Outputs" \
            --output table
